/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkjVue;

import org.hibernate.Session;
import pkgEntite.HibernateUtil;

/**
 *
 * @author etudSIO
 */
public class jfPrincipal extends javax.swing.JFrame {
    //déclaration d'un panel
    protected jpTypeChambre jpnlTypeChambre= new jpTypeChambre();
    //Déclaration d'une session commune aux différents interfaces
        private static Session session= HibernateUtil.getSessionFactory().openSession();
        
    /**
     * Creates new form jfPrincipal
     */
    public jfPrincipal() {
        initComponents();
    }

    public static Session getSession() {
        return session;
    }

    public static void setSession(Session psession) {
        jfPrincipal.session = psession;
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmAccueil = new javax.swing.JMenu();
        jmEtablissement = new javax.swing.JMenu();
        jmiEvoir = new javax.swing.JMenuItem();
        jmiEajouter = new javax.swing.JMenuItem();
        jmiEmodifier = new javax.swing.JMenuItem();
        jmiEsupprimer = new javax.swing.JMenuItem();
        jmTypeChambre = new javax.swing.JMenu();
        jmiTvoir = new javax.swing.JMenuItem();
        jmiTajouter = new javax.swing.JMenuItem();
        jmiTmodifier = new javax.swing.JMenuItem();
        jmiTsupprimer = new javax.swing.JMenuItem();
        jmHebergement = new javax.swing.JMenu();
        jmiHvoir = new javax.swing.JMenuItem();
        jmiHmodifier = new javax.swing.JMenuItem();
        jmChambres = new javax.swing.JMenu();
        jmiCvoir = new javax.swing.JMenuItem();
        jmiCmodifier = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmAccueil.setText("Accueil");
        jMenuBar1.add(jmAccueil);

        jmEtablissement.setText("Gestion établissement");

        jmiEvoir.setText("Voir");
        jmEtablissement.add(jmiEvoir);

        jmiEajouter.setText("Ajouter");
        jmEtablissement.add(jmiEajouter);

        jmiEmodifier.setText("Modifier");
        jmEtablissement.add(jmiEmodifier);

        jmiEsupprimer.setText("Supprimer");
        jmEtablissement.add(jmiEsupprimer);

        jMenuBar1.add(jmEtablissement);

        jmTypeChambre.setText("Gestion type de chambre");

        jmiTvoir.setText("Voir");
        jmiTvoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTvoirActionPerformed(evt);
            }
        });
        jmTypeChambre.add(jmiTvoir);

        jmiTajouter.setText("Ajouter");
        jmTypeChambre.add(jmiTajouter);

        jmiTmodifier.setText("Modifier");
        jmiTmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTmodifierActionPerformed(evt);
            }
        });
        jmTypeChambre.add(jmiTmodifier);

        jmiTsupprimer.setText("Supprimer");
        jmTypeChambre.add(jmiTsupprimer);

        jMenuBar1.add(jmTypeChambre);

        jmHebergement.setText("Offre hebergement");

        jmiHvoir.setText("Voir");
        jmHebergement.add(jmiHvoir);

        jmiHmodifier.setText("Modifier");
        jmHebergement.add(jmiHmodifier);

        jMenuBar1.add(jmHebergement);

        jmChambres.setText("Attribution Chambres");

        jmiCvoir.setText("Voir");
        jmChambres.add(jmiCvoir);

        jmiCmodifier.setText("Modifier");
        jmChambres.add(jmiCmodifier);

        jMenuBar1.add(jmChambres);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiTmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTmodifierActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmiTmodifierActionPerformed

    private void jmiTvoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTvoirActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jpnlTypeChambre);
        pack();
    }//GEN-LAST:event_jmiTvoirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAccueil;
    private javax.swing.JMenu jmChambres;
    private javax.swing.JMenu jmEtablissement;
    private javax.swing.JMenu jmHebergement;
    private javax.swing.JMenu jmTypeChambre;
    private javax.swing.JMenuItem jmiCmodifier;
    private javax.swing.JMenuItem jmiCvoir;
    private javax.swing.JMenuItem jmiEajouter;
    private javax.swing.JMenuItem jmiEmodifier;
    private javax.swing.JMenuItem jmiEsupprimer;
    private javax.swing.JMenuItem jmiEvoir;
    private javax.swing.JMenuItem jmiHmodifier;
    private javax.swing.JMenuItem jmiHvoir;
    private javax.swing.JMenuItem jmiTajouter;
    private javax.swing.JMenuItem jmiTmodifier;
    private javax.swing.JMenuItem jmiTsupprimer;
    private javax.swing.JMenuItem jmiTvoir;
    // End of variables declaration//GEN-END:variables
}
