/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkjVue;

import org.hibernate.Session;
import pkgEntite.HibernateUtil;
import pkjVue.jfPrincipal;

/**
 *
 * @author etudSIO
 */
public class jpTypeChambre extends javax.swing.JPanel {
   
    /**
     * Creates new form jpTypeChambre
     */
    
    public jpTypeChambre() {
        initComponents();
     
    }

    
    public void jtblTypeChambreAction(java.awt.event.ActionEvent evt){
        String sCode;
        String sQuery;
        int l=0;
        int inbligne;
        int i;
        sQuery="From Typechambre";
        jfPrincipal.getSession().beginTransaction();
        
        
        
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTypeChambre = new javax.swing.JTable();

        jLabel1.setText("TYPE DE CHAMBRE");

        jtblTypeChambre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Code", "Nombre de liits"
            }
        ));
        jScrollPane1.setViewportView(jtblTypeChambre);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(142, 142, 142)
                .add(jLabel1)
                .addContainerGap(167, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(45, 45, 45)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblTypeChambre;
    // End of variables declaration//GEN-END:variables
}
